export const emojiTabList = [
    { id: 'emoji1', text: '😆' },
    { id: 'emoji2', text: '👩🏿' },
    { id: 'emoji3', text: '🎈' },
    { id: 'emoji4', text: '🍔' },
    { id: 'emoji5', text: '🚗' },
    { id: 'emoji6', text: '❤' },
]

export const emojiTabPaneMap = {
    emoji1: [
        { id: 'emoji1-01', text: '😀' },
        { id: 'emoji1-02', text: '😁' },
        { id: 'emoji1-03', text: '😂' },
        { id: 'emoji1-04', text: '🤣' },
        { id: 'emoji1-05', text: '😃' },
        { id: 'emoji1-06', text: '😄' },
        { id: 'emoji1-07', text: '😅' },
        { id: 'emoji1-08', text: '😆' },
        { id: 'emoji1-09', text: '😉' },
        { id: 'emoji1-10', text: '😊' },
        { id: 'emoji1-11', text: '😋' },
        { id: 'emoji1-12', text: '😎' },
        { id: 'emoji1-13', text: '😍' },
        { id: 'emoji1-14', text: '😘' },
        { id: 'emoji1-15', text: '🥰' },
        { id: 'emoji1-16', text: '😗' },
        { id: 'emoji1-17', text: '😙' },
        { id: 'emoji1-18', text: '😚' },
        { id: 'emoji1-19', text: '🙂' },
        { id: 'emoji1-20', text: '🤗' },
        { id: 'emoji1-21', text: '🤔' },
        { id: 'emoji1-22', text: '🤨' },
        { id: 'emoji1-23', text: '🤩' },
    ],
    emoji2: [
        { id: 'emiji2-01', text: '👩🏿' },
        { id: 'emiji2-02', text: '👨🏿' },
        { id: 'emiji2-03', text: '🧑🏿' },
        { id: 'emiji2-04', text: '👧🏿' },
        { id: 'emiji2-05', text: '👦🏿' },
        { id: 'emiji2-06', text: '🧒🏿' },
        { id: 'emiji2-07', text: '👶🏿' },
        { id: 'emiji2-08', text: '👵🏿' },
        { id: 'emiji2-09', text: '👴🏿' },
        { id: 'emiji2-10', text: '🧓🏿' },
        { id: 'emiji2-11', text: '👩🏿‍🦰' },
        { id: 'emiji2-12', text: '👨🏿‍🦰' },
        { id: 'emiji2-13', text: '👩🏿‍🦱' },
        { id: 'emiji2-14', text: '👨🏿‍🦱' },
        { id: 'emiji2-15', text: '👩🏿‍🦲' },
        { id: 'emiji2-16', text: '👩🏿‍🦳' },
        { id: 'emiji2-17', text: '👨🏿‍🦳' },
        { id: 'emiji2-18', text: '👱🏿‍♀️' },
    ],
};